export const GET_ERRORS = 'GET_ERRORS';
export const LOG_IN= 'LOG_IN';
export const CURRENT_USER= 'CURRENT_USER';
export const CURRENT_RECORDS= 'CURRENT_RECORDS';
export const GET_USERS= 'GET_USERS';
export const GET_USERS_POSTS= 'GET_USERS_POSTS';
export const LOGOUT ='LOGOUT'
export const DELETE_USER ='DELETE_USER '
export const SAVE_POST = 'SAVE_POST';
export const SEARCH_POSTS = 'SEARCH_POSTS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_POSTS = 'GET_POSTS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERRORS = 'PROFILE_ERRORS';
export const UPDATE_POST = 'UPDATE_POST';
export const SET_ALERT = 'SET_ALERTS';
export const  REMOVE_ALERTS = 'REMOVE_ALERTS';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const POST_ERROR = 'POST_ERROR';